export const country = [
  {
    name: "Algeria",
    code: "DZ",
    capital: "Algiers",
    population: 43851044,
    area: { number: 2381741, measure: "sq km" },
    currency: { name: "Algerian Dinar", code: "DZD" },
    languages: ["Arabic", "Tamazight"],
    telephone_code: "+213",
  },
  {
    name: "Angola",
    code: "AO",
    capital: "Luanda",
    population: 32866272,
    area: { number: 1246700, measure: "sq km" },
    currency: { name: "Angolan Kwanza", code: "AOA" },
    languages: ["Portuguese"],
    telephone_code: "+244",
  },
  {
    name: "Benin",
    code: "BJ",
    capital: "Porto-Novo",
    population: 12123200,
    area: { number: 112622, measure: "sq km" },
    currency: { name: "West African CFA franc", code: "XOF" },
    languages: ["French"],
    telephone_code: "+229",
  },
  {
    name: "Botswana",
    code: "BW",
    capital: "Gaborone",
    population: 2351627,
    area: { number: 581730, measure: "sq km" },
    currency: { name: "Botswana Pula", code: "BWP" },
    languages: ["English", "Setswana"],
    telephone_code: "+267",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    capital: "Ouagadougou",
    population: 20870060,
    area: { number: 274200, measure: "sq km" },
    currency: { name: "West African CFA franc", code: "XOF" },
    languages: ["French"],
    telephone_code: "+226",
  },
  {
    name: "Burundi",
    code: "BI",
    capital: "Bujumbura",
    population: 11890784,
    area: { number: 27834, measure: "sq km" },
    currency: { name: "Burundian Franc", code: "BIF" },
    languages: ["Kirundi", "French"],
    telephone_code: "+257",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    capital: "Praia",
    population: 556857,
    area: { number: 4033, measure: "sq km" },
    currency: { name: "Cape Verdean Escudo", code: "CVE" },
    languages: ["Portuguese"],
    telephone_code: "+238",
  },
  {
    name: "Cameroon",
    code: "CM",
    capital: "Yaoundé",
    population: 26545863,
    area: { number: 475442, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["French", "English"],
    telephone_code: "+237",
  },
  {
    name: "Central African Republic",
    code: "CF",
    capital: "Bangui",
    population: 4829764,
    area: { number: 622984, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["French", "Sango"],
    telephone_code: "+236",
  },
  {
    name: "Chad",
    code: "TD",
    capital: "N'Djamena",
    population: 16425859,
    area: { number: 1284000, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["French", "Arabic"],
    telephone_code: "+235",
  },

  {
    name: "Comoros",
    code: "KM",
    capital: "Moroni",
    population: 869601,
    area: { number: 1862, measure: "sq km" },
    currency: { name: "Comorian Franc", code: "KMF" },
    languages: ["Arabic", "French", "Comorian"],
    telephone_code: "+269",
  },
  {
    name: "Congo (Brazzaville)",
    code: "CG",
    capital: "Brazzaville",
    population: 5662259,
    area: { number: 342000, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["French"],
    telephone_code: "+242",
  },
  {
    name: "Congo (Kinshasa)",
    code: "CD",
    capital: "Kinshasa",
    population: 101780263,
    area: { number: 2344858, measure: "sq km" },
    currency: { name: "Congolese Franc", code: "CDF" },
    languages: ["French", "Lingala", "Kongo", "Swahili", "Tshiluba"],
    telephone_code: "+243",
  },
  {
    name: "Djibouti",
    code: "DJ",
    capital: "Djibouti",
    population: 1009722,
    area: { number: 23200, measure: "sq km" },
    currency: { name: "Djiboutian Franc", code: "DJF" },
    languages: ["French", "Arabic"],
    telephone_code: "+253",
  },
  {
    name: "Egypt",
    code: "EG",
    capital: "Cairo",
    population: 104258327,
    area: { number: 1002450, measure: "sq km" },
    currency: { name: "Egyptian Pound", code: "EGP" },
    languages: ["Arabic"],
    telephone_code: "+20",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    capital: "Malabo",
    population: 1402985,
    area: { number: 28051, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["Spanish", "French", "Portuguese"],
    telephone_code: "+240",
  },
  {
    name: "Eritrea",
    code: "ER",
    capital: "Asmara",
    population: 3546421,
    area: { number: 117600, measure: "sq km" },
    currency: { name: "Eritrean Nakfa", code: "ERN" },
    languages: ["Tigrinya", "Arabic", "English"],
    telephone_code: "+291",
  },
  {
    name: "Eswatini",
    code: "SZ",
    capital: "Mbabane",
    population: 1160164,
    area: { number: 17364, measure: "sq km" },
    currency: { name: "Swazi Lilangeni", code: "SZL" },
    languages: ["English", "Swati"],
    telephone_code: "+268",
  },
  {
    name: "Ethiopia",
    code: "ET",
    capital: "Addis Ababa",
    population: 117876693,
    area: { number: 1104300, measure: "sq km" },
    currency: { name: "Ethiopian Birr", code: "ETB" },
    languages: ["Amharic"],
    telephone_code: "+251",
  },
  {
    name: "Gabon",
    code: "GA",
    capital: "Libreville",
    population: 2297338,
    area: { number: 267668, measure: "sq km" },
    currency: { name: "Central African CFA franc", code: "XAF" },
    languages: ["French"],
    telephone_code: "+241",
  },

  {
    name: "Gambia",
    code: "GM",
    capital: "Banjul",
    population: 2416668,
    area: {
      number: 10689,
      measure: "sq km",
    },
    currency: {
      name: "Gambian Dalasi",
      code: "GMD",
    },
    languages: ["English"],
    telephone_code: "+220",
  },
  {
    name: "Ghana",
    code: "GH",
    capital: "Accra",
    population: 31072940,
    area: {
      number: 238533,
      measure: "sq km",
    },
    currency: {
      name: "Ghanaian Cedi",
      code: "GHS",
    },
    languages: ["English"],
    telephone_code: "+233",
  },
  {
    name: "Guinea",
    code: "GN",
    capital: "Conakry",
    population: 13914038,
    area: {
      number: 245857,
      measure: "sq km",
    },
    currency: {
      name: "Guinean Franc",
      code: "GNF",
    },
    languages: ["French"],
    telephone_code: "+224",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    capital: "Bissau",
    population: 2090462,
    area: {
      number: 36125,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["Portuguese"],
    telephone_code: "+245",
  },
  {
    name: "Ivory Coast",
    code: "CI",
    capital: "Yamoussoukro",
    population: 27466084,
    area: {
      number: 322463,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["French"],
    telephone_code: "+225",
  },
  {
    name: "Kenya",
    code: "KE",
    capital: "Nairobi",
    population: 55414168,
    area: {
      number: 580367,
      measure: "sq km",
    },
    currency: {
      name: "Kenyan Shilling",
      code: "KES",
    },
    languages: ["Swahili", "English"],
    telephone_code: "+254",
  },
  {
    name: "Lesotho",
    code: "LS",
    capital: "Maseru",
    population: 2156102,
    area: {
      number: 30355,
      measure: "sq km",
    },
    currency: {
      name: "Lesotho Loti",
      code: "LSL",
    },
    languages: ["English", "Sesotho"],
    telephone_code: "+266",
  },
  {
    name: "Liberia",
    code: "LR",
    capital: "Monrovia",
    population: 5217128,
    area: {
      number: 111369,
      measure: "sq km",
    },
    currency: {
      name: "Liberian Dollar",
      code: "LRD",
    },
    languages: ["English"],
    telephone_code: "+231",
  },
  {
    name: "Libya",
    code: "LY",
    capital: "Tripoli",
    population: 6976605,
    area: {
      number: 1759540,
      measure: "sq km",
    },
    currency: {
      name: "Libyan Dinar",
      code: "LYD",
    },
    languages: ["Arabic"],
    telephone_code: "+218",
  },
  {
    name: "Madagascar",
    code: "MG",
    capital: "Antananarivo",
    population: 28287847,
    area: {
      number: 587041,
      measure: "sq km",
    },
    currency: {
      name: "Malagasy Ariary",
      code: "MGA",
    },
    languages: ["Malagasy", "French"],
    telephone_code: "+261",
  },

  {
    name: "Malawi",
    code: "MW",
    capital: "Lilongwe",
    population: 20201932,
    area: {
      number: 118484,
      measure: "sq km",
    },
    currency: {
      name: "Malawian Kwacha",
      code: "MWK",
    },
    languages: ["English", "Chichewa"],
    telephone_code: "+265",
  },
  {
    name: "Mali",
    code: "ML",
    capital: "Bamako",
    population: 20250833,
    area: {
      number: 1240192,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["French"],
    telephone_code: "+223",
  },
  {
    name: "Mauritania",
    code: "MR",
    capital: "Nouakchott",
    population: 4801000,
    area: {
      number: 1030700,
      measure: "sq km",
    },
    currency: {
      name: "Mauritanian Ouguiya",
      code: "MRU",
    },
    languages: ["Arabic"],
    telephone_code: "+222",
  },
  {
    name: "Mauritius",
    code: "MU",
    capital: "Port Louis",
    population: 1271768,
    area: {
      number: 2040,
      measure: "sq km",
    },
    currency: {
      name: "Mauritian Rupee",
      code: "MUR",
    },
    languages: ["English", "French", "Mauritian Creole"],
    telephone_code: "+230",
  },
  {
    name: "Morocco",
    code: "MA",
    capital: "Rabat",
    population: 37172000,
    area: {
      number: 446550,
      measure: "sq km",
    },
    currency: {
      name: "Moroccan Dirham",
      code: "MAD",
    },
    languages: ["Arabic", "Berber"],
    telephone_code: "+212",
  },
  {
    name: "Mozambique",
    code: "MZ",
    capital: "Maputo",
    population: 31255435,
    area: {
      number: 801590,
      measure: "sq km",
    },
    currency: {
      name: "Mozambican Metical",
      code: "MZN",
    },
    languages: ["Portuguese"],
    telephone_code: "+258",
  },
  {
    name: "Namibia",
    code: "NA",
    capital: "Windhoek",
    population: 2540905,
    area: {
      number: 825615,
      measure: "sq km",
    },
    currency: {
      name: "Namibian Dollar",
      code: "NAD",
    },
    languages: ["English", "Afrikaans"],
    telephone_code: "+264",
  },
  {
    name: "Niger",
    code: "NE",
    capital: "Niamey",
    population: 24194346,
    area: {
      number: 1267000,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["French"],
    telephone_code: "+227",
  },
  {
    name: "Nigeria",
    code: "NG",
    capital: "Abuja",
    population: 206139589,
    area: {
      number: 923768,
      measure: "sq km",
    },
    currency: {
      name: "Nigerian Naira",
      code: "NGN",
    },
    languages: ["English"],
    telephone_code: "+234",
  },
  {
    name: "Rwanda",
    code: "RW",
    capital: "Kigali",
    population: 12952218,
    area: {
      number: 26338,
      measure: "sq km",
    },
    currency: {
      name: "Rwandan Franc",
      code: "RWF",
    },
    languages: ["Kinyarwanda", "English", "French", "Swahili"],
    telephone_code: "+250",
  },

  {
    name: "Sao Tome and Principe",
    code: "ST",
    capital: "São Tomé",
    population: 219159,
    area: {
      number: 964,
      measure: "sq km",
    },
    currency: {
      name: "São Tomé and Príncipe Dobra",
      code: "STD",
    },
    languages: ["Portuguese"],
    telephone_code: "+239",
  },
  {
    name: "Senegal",
    code: "SN",
    capital: "Dakar",
    population: 16743930,
    area: {
      number: 196722,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["French"],
    telephone_code: "+221",
  },
  {
    name: "Seychelles",
    code: "SC",
    capital: "Victoria",
    population: 98347,
    area: {
      number: 459,
      measure: "sq km",
    },
    currency: {
      name: "Seychellois Rupee",
      code: "SCR",
    },
    languages: ["Seychellois Creole", "English", "French"],
    telephone_code: "+248",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    capital: "Freetown",
    population: 7976983,
    area: {
      number: 71740,
      measure: "sq km",
    },
    currency: {
      name: "Sierra Leonean Leone",
      code: "SLL",
    },
    languages: ["English"],
    telephone_code: "+232",
  },
  {
    name: "Somalia",
    code: "SO",
    capital: "Mogadishu",
    population: 15893219,
    area: {
      number: 637657,
      measure: "sq km",
    },
    currency: {
      name: "Somali Shilling",
      code: "SOS",
    },
    languages: ["Somali", "Arabic"],
    telephone_code: "+252",
  },
  {
    name: "South Africa",
    code: "ZA",
    capital: "Cape Town",
    population: 60041959,
    area: {
      number: 1221037,
      measure: "sq km",
    },
    currency: {
      name: "South African Rand",
      code: "ZAR",
    },
    languages: [
      "Afrikaans",
      "English",
      "Zulu",
      "Xhosa",
      "Swazi",
      "Tsonga",
      "Southern Ndebele",
      "Northern Sotho",
      "Southern Sotho",
      "Tswana",
      "Venda",
    ],
    telephone_code: "+27",
  },
  {
    name: "South Sudan",
    code: "SS",
    capital: "Juba",
    population: 11193725,
    area: {
      number: 619745,
      measure: "sq km",
    },
    currency: {
      name: "South Sudanese Pound",
      code: "SSP",
    },
    languages: ["English"],
    telephone_code: "+211",
  },
  {
    name: "Sudan",
    code: "SD",
    capital: "Khartoum",
    population: 43849260,
    area: {
      number: 1886068,
      measure: "sq km",
    },
    currency: {
      name: "Sudanese Pound",
      code: "SDG",
    },
    languages: ["Arabic", "English"],
    telephone_code: "+249",
  },
  {
    name: "Tanzania",
    code: "TZ",
    capital: "Dodoma",
    population: 59734218,
    area: {
      number: 947300,
      measure: "sq km",
    },
    currency: {
      name: "Tanzanian Shilling",
      code: "TZS",
    },
    languages: ["Swahili", "English"],
    telephone_code: "+255",
  },
  {
    name: "Togo",
    code: "TG",
    capital: "Lomé",
    population: 8278724,
    area: {
      number: 56785,
      measure: "sq km",
    },
    currency: {
      name: "West African CFA franc",
      code: "XOF",
    },
    languages: ["French"],
    telephone_code: "+228",
  },
  {
    name: "Tunisia",
    code: "TN",
    capital: "Tunis",
    population: 11818619,
    area: {
      number: 163610,
      measure: "sq km",
    },
    currency: {
      name: "Tunisian Dinar",
      code: "TND",
    },
    languages: ["Arabic"],
    telephone_code: "+216",
  },
  {
    name: "Uganda",
    code: "UG",
    capital: "Kampala",
    population: 47101700,
    area: {
      number: 241550,
      measure: "sq km",
    },
    currency: {
      name: "Ugandan Shilling",
      code: "UGX",
    },
    languages: ["English", "Swahili"],
    telephone_code: "+256",
  },
  {
    name: "Zambia",
    code: "ZM",
    capital: "Lusaka",
    population: 18383956,
    area: {
      number: 752612,
      measure: "sq km",
    },
    currency: {
      name: "Zambian Kwacha",
      code: "ZMW",
    },
    languages: ["English"],
    telephone_code: "+260",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    capital: "Harare",
    population: 14899771,
    area: {
      number: 390757,
      measure: "sq km",
    },
    currency: {
      name: "Zimbabwean Dollar",
      code: "ZWL",
    },
    languages: ["English", "Shona", "Ndebele"],
    telephone_code: "+263",
  },
];
