export const country = [
  {
    name: "Afghanistan",
    code: "AF",
    capital: "Kabul",
    population: 38928346,
    area: { number: 652230, measure: "sq km" },
    currency_name: "Afghan Afghani",
    currency_code: "AFN",
    languages: ["Pashto", "Dari"],
    telephone_code: "+93",
  },
  {
    name: "Armenia",
    code: "AM",
    capital: "Yerevan",
    population: 2963243,
    area: { number: 29743, measure: "sq km" },
    currency_name: "Armenian Dram",
    currency_code: "AMD",
    languages: ["Armenian"],
    telephone_code: "+374",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    capital: "Baku",
    population: 10139177,
    area: { number: 86600, measure: "sq km" },
    currency_name: "Azerbaijani Manat",
    currency_code: "AZN",
    languages: ["Azerbaijani"],
    telephone_code: "+994",
  },
  {
    name: "Bahrain",
    code: "BH",
    capital: "Manama",
    population: 1701575,
    area: { number: 780, measure: "sq km" },
    currency_name: "Bahraini Dinar",
    currency_code: "BHD",
    languages: ["Arabic"],
    telephone_code: "+973",
  },
  {
    name: "Bangladesh",
    code: "BD",
    capital: "Dhaka",
    population: 164689383,
    area: { number: 147570, measure: "sq km" },
    currency_name: "Bangladeshi Taka",
    currency_code: "BDT",
    languages: ["Bengali"],
    telephone_code: "+880",
  },
  {
    name: "Bhutan",
    code: "BT",
    capital: "Thimphu",
    population: 771608,
    area: { number: 38394, measure: "sq km" },
    currency_name: "Bhutanese Ngultrum",
    currency_code: "BTN",
    languages: ["Dzongkha"],
    telephone_code: "+975",
  },
  {
    name: "Brunei",
    code: "BN",
    capital: "Bandar Seri Begawan",
    population: 437479,
    area: { number: 5765, measure: "sq km" },
    currency_name: "Brunei Dollar",
    currency_code: "BND",
    languages: ["Malay"],
    telephone_code: "+673",
  },
  {
    name: "Cambodia",
    code: "KH",
    capital: "Phnom Penh",
    population: 16718965,
    area: { number: 181035, measure: "sq km" },
    currency_name: "Cambodian Riel",
    currency_code: "KHR",
    languages: ["Khmer"],
    telephone_code: "+855",
  },
  {
    name: "China",
    code: "CN",
    capital: "Beijing",
    population: 1439323776,
    area: { number: 9706961, measure: "sq km" },
    currency_name: "Chinese Yuan",
    currency_code: "CNY",
    languages: ["Mandarin"],
    telephone_code: "+86",
  },


  {
    name: "Georgia",
    code: "GE",
    capital: "Tbilisi",
    population: 3989167,
    area: { number: 69700, measure: "sq km" },
    currency_name: "Georgian Lari",
    currency_code: "GEL",
    languages: ["Georgian"],
    telephone_code: "+995",
  },
  {
    name: "India",
    code: "IN",
    capital: "New Delhi",
    population: 1380004385,
    area: { number: 3287263, measure: "sq km" },
    currency_name: "Indian Rupee",
    currency_code: "INR",
    languages: ["Hindi", "English"],
    telephone_code: "+91",
  },
  {
    name: "Indonesia",
    code: "ID",
    capital: "Jakarta",
    population: 273523615,
    area: { number: 1904569, measure: "sq km" },
    currency_name: "Indonesian Rupiah",
    currency_code: "IDR",
    languages: ["Indonesian"],
    telephone_code: "+62",
  },
  {
    name: "Iran",
    code: "IR",
    capital: "Tehran",
    population: 83992949,
    area: { number: 1648195, measure: "sq km" },
    currency_name: "Iranian Rial",
    currency_code: "IRR",
    languages: ["Persian"],
    telephone_code: "+98",
  },
  {
    name: "Iraq",
    code: "IQ",
    capital: "Baghdad",
    population: 40222493,
    area: { number: 438317, measure: "sq km" },
    currency_name: "Iraqi Dinar",
    currency_code: "IQD",
    languages: ["Arabic", "Kurdish"],
    telephone_code: "+964",
  },
  {
    name: "Israel",
    code: "IL",
    capital: "Jerusalem",
    population: 8655535,
    area: { number: 20770, measure: "sq km" },
    currency_name: "Israeli New Shekel",
    currency_code: "ILS",
    languages: ["Hebrew", "Arabic"],
    telephone_code: "+972",
  },
  {
    name: "Japan",
    code: "JP",
    capital: "Tokyo",
    population: 126476461,
    area: { number: 377975, measure: "sq km" },
    currency_name: "Japanese Yen",
    currency_code: "JPY",
    languages: ["Japanese"],
    telephone_code: "+81",
  },
  {
    name: "Jordan",
    code: "JO",
    capital: "Amman",
    population: 10203134,
    area: { number: 89342, measure: "sq km" },
    currency_name: "Jordanian Dinar",
    currency_code: "JOD",
    languages: ["Arabic"],
    telephone_code: "+962",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    capital: "Nur-Sultan",
    population: 18776707,
    area: { number: 2724900, measure: "sq km" },
    currency_name: "Kazakhstani Tenge",
    currency_code: "KZT",
    languages: ["Kazakh", "Russian"],
    telephone_code: "+7",
  },
  {
    name: "Kuwait",
    code: "KW",
    capital: "Kuwait City",
    population: 4270571,
    area: { number: 17818, measure: "sq km" },
    currency_name: "Kuwaiti Dinar",
    currency_code: "KWD",
    languages: ["Arabic"],
    telephone_code: "+965",
  },

  {
    name: "Kyrgyzstan",
    code: "KG",
    capital: "Bishkek",
    population: 6524195,
    area: { number: 199951, measure: "sq km" },
    currency_name: "Kyrgyzstani Som",
    currency_code: "KGS",
    languages: ["Kyrgyz", "Russian"],
    telephone_code: "+996",
  },
  {
    name: "Laos",
    code: "LA",
    capital: "Vientiane",
    population: 7275560,
    area: { number: 236800, measure: "sq km" },
    currency_name: "Lao Kip",
    currency_code: "LAK",
    languages: ["Lao"],
    telephone_code: "+856",
  },
  {
    name: "Lebanon",
    code: "LB",
    capital: "Beirut",
    population: 6825442,
    area: { number: 10452, measure: "sq km" },
    currency_name: "Lebanese Pound",
    currency_code: "LBP",
    languages: ["Arabic"],
    telephone_code: "+961",
  },
  {
    name: "Malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    population: 32365999,
    area: { number: 330803, measure: "sq km" },
    currency_name: "Malaysian Ringgit",
    currency_code: "MYR",
    languages: ["Malay"],
    telephone_code: "+60",
  },
  {
    name: "Maldives",
    code: "MV",
    capital: "Malé",
    population: 540542,
    area: { number: 300, measure: "sq km" },
    currency_name: "Maldivian Rufiyaa",
    currency_code: "MVR",
    languages: ["Dhivehi"],
    telephone_code: "+960",
  },
  {
    name: "Mongolia",
    code: "MN",
    capital: "Ulaanbaatar",
    population: 3278290,
    area: { number: 1564116, measure: "sq km" },
    currency_name: "Mongolian Tögrög",
    currency_code: "MNT",
    languages: ["Mongolian"],
    telephone_code: "+976",
  },
  {
    name: "Myanmar",
    code: "MM",
    capital: "Naypyidaw",
    population: 54409800,
    area: { number: 676578, measure: "sq km" },
    currency_name: "Burmese Kyat",
    currency_code: "MMK",
    languages: ["Burmese"],
    telephone_code: "+95",
  },
  {
    name: "Nepal",
    code: "NP",
    capital: "Kathmandu",
    population: 29136808,
    area: { number: 147516, measure: "sq km" },
    currency_name: "Nepalese Rupee",
    currency_code: "NPR",
    languages: ["Nepali"],
    telephone_code: "+977",
  },
  {
    name: "North Korea",
    code: "KP",
    capital: "Pyongyang",
    population: 25778816,
    area: { number: 120538, measure: "sq km" },
    currency_name: "North Korean Won",
    currency_code: "KPW",
    languages: ["Korean"],
    telephone_code: "+850",
  },
  {
    name: "Oman",
    code: "OM",
    capital: "Muscat",
    population: 5106622,
    area: { number: 309500, measure: "sq km" },
    currency_name: "Omani Rial",
    currency_code: "OMR",
    languages: ["Arabic"],
    telephone_code: "+968",
  },

  {
    name: "Pakistan",
    code: "PK",
    capital: "Islamabad",
    population: 220892340,
    area: { number: 881913, measure: "sq km" },
    currency_name: "Pakistani Rupee",
    currency_code: "PKR",
    languages: ["Urdu", "English"],
    telephone_code: "+92",
  },
  {
    name: "Palestine",
    code: "PS",
    capital: "East Jerusalem",
    population: 5228161,
    area: { number: 6220, measure: "sq km" },
    currency_name: "Israeli New Shekel, Jordanian Dinar, Euro, Egyptian Pound",
    currency_code: "ILS, JOD, EUR, EGP",
    languages: ["Arabic"],
    telephone_code: "+970",
  },
  {
    name: "Philippines",
    code: "PH",
    capital: "Manila",
    population: 109581078,
    area: { number: 342353, measure: "sq km" },
    currency_name: "Philippine Peso",
    currency_code: "PHP",
    languages: ["Filipino", "English"],
    telephone_code: "+63",
  },
  {
    name: "Qatar",
    code: "QA",
    capital: "Doha",
    population: 2881053,
    area: { number: 11586, measure: "sq km" },
    currency_name: "Qatari Riyal",
    currency_code: "QAR",
    languages: ["Arabic"],
    telephone_code: "+974",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    capital: "Riyadh",
    population: 34813867,
    area: { number: 2149690, measure: "sq km" },
    currency_name: "Saudi Riyal",
    currency_code: "SAR",
    languages: ["Arabic"],
    telephone_code: "+966",
  },
  {
    name: "Singapore",
    code: "SG",
    capital: "Singapore",
    population: 5850342,
    area: { number: 726, measure: "sq km" },
    currency_name: "Singapore Dollar",
    currency_code: "SGD",
    languages: ["English", "Malay", "Mandarin", "Tamil"],
    telephone_code: "+65",
  },
  {
    name: "South Korea",
    code: "KR",
    capital: "Seoul",
    population: 51269185,
    area: { number: 100210, measure: "sq km" },
    currency_name: "South Korean Won",
    currency_code: "KRW",
    languages: ["Korean"],
    telephone_code: "+82",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    capital: "Colombo, Sri Jayawardenepura Kotte",
    population: 21413249,
    area: { number: 65610, measure: "sq km" },
    currency_name: "Sri Lankan Rupee",
    currency_code: "LKR",
    languages: ["Sinhala", "Tamil"],
    telephone_code: "+94",
  },
  {
    name: "Syria",
    code: "SY",
    capital: "Damascus",
    population: 17500658,
    area: { number: 185180, measure: "sq km" },
    currency_name: "Syrian Pound",
    currency_code: "SYP",
    languages: ["Arabic"],
    telephone_code: "+963",
  },
  {
    name: "Taiwan",
    code: "TW",
    capital: "Taipei",
    population: 23816775,
    area: { number: 36193, measure: "sq km" },
    currency_name: "New Taiwan Dollar",
    currency_code: "TWD",
    languages: ["Mandarin"],
    telephone_code: "+886",
  },

  {
    name: "Tajikistan",
    code: "TJ",
    capital: "Dushanbe",
    population: 9537645,
    area: { number: 143100, measure: "sq km" },
    currency_name: "Tajikistani Somoni",
    currency_code: "TJS",
    languages: ["Tajik", "Russian"],
    telephone_code: "+992",
  },
  {
    name: "Thailand",
    code: "TH",
    capital: "Bangkok",
    population: 69799978,
    area: { number: 513120, measure: "sq km" },
    currency_name: "Thai Baht",
    currency_code: "THB",
    languages: ["Thai"],
    telephone_code: "+66",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    capital: "Dili",
    population: 1318445,
    area: { number: 14874, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["Portuguese", "Tetum"],
    telephone_code: "+670",
  },
  {
    name: "Turkey",
    code: "TR",
    capital: "Ankara",
    population: 84339067,
    area: { number: 783356, measure: "sq km" },
    currency_name: "Turkish Lira",
    currency_code: "TRY",
    languages: ["Turkish"],
    telephone_code: "+90",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    capital: "Ashgabat",
    population: 6031187,
    area: { number: 488100, measure: "sq km" },
    currency_name: "Turkmenistan Manat",
    currency_code: "TMT",
    languages: ["Turkmen", "Russian"],
    telephone_code: "+993",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    capital: "Abu Dhabi",
    population: 9890402,
    area: { number: 83600, measure: "sq km" },
    currency_name: "United Arab Emirates Dirham",
    currency_code: "AED",
    languages: ["Arabic"],
    telephone_code: "+971",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    capital: "Tashkent",
    population: 33469203,
    area: { number: 447400, measure: "sq km" },
    currency_name: "Uzbekistani Som",
    currency_code: "UZS",
    languages: ["Uzbek", "Russian"],
    telephone_code: "+998",
  },
  {
    name: "Vietnam",
    code: "VN",
    capital: "Hanoi",
    population: 97338579,
    area: { number: 331212, measure: "sq km" },
    currency_name: "Vietnamese Dong",
    currency_code: "VND",
    languages: ["Vietnamese"],
    telephone_code: "+84",
  },
  {
    name: "Yemen",
    code: "YE",
    capital: "Sana'a",
    population: 29825964,
    area: { number: 527968, measure: "sq km" },
    currency_name: "Yemeni Rial",
    currency_code: "YER",
    languages: ["Arabic"],
    telephone_code: "+967",
  },
];
