export const country = [
  {
    name: "Australia",
    code: "AU",
    capital: "Canberra",
    population: 25499884,
    area: { number: 7692024, measure: "sq km" },
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    languages: ["English"],
    telephone_code: "+61",
  },
  {
    name: "Fiji",
    code: "FJ",
    capital: "Suva",
    population: 896445,
    area: { number: 18272, measure: "sq km" },
    currency_name: "Fijian Dollar",
    currency_code: "FJD",
    languages: ["English", "Fijian", "Hindi"],
    telephone_code: "+679",
  },
  {
    name: "Kiribati",
    code: "KI",
    capital: "South Tarawa",
    population: 119449,
    area: { number: 811, measure: "sq km" },
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    languages: ["English", "Gilbertese"],
    telephone_code: "+686",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    capital: "Majuro",
    population: 59190,
    area: { number: 181, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["English", "Marshallese"],
    telephone_code: "+692",
  },
  {
    name: "Micronesia",
    code: "FM",
    capital: "Palikir",
    population: 115023,
    area: { number: 702, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["English"],
    telephone_code: "+691",
  },
  {
    name: "Nauru",
    code: "NR",
    capital: "Yaren",
    population: 10824,
    area: { number: 21, measure: "sq km" },
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    languages: ["English", "Nauruan"],
    telephone_code: "+674",
  },
  {
    name: "New Zealand",
    code: "NZ",
    capital: "Wellington",
    population: 4822233,
    area: { number: 270467, measure: "sq km" },
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    languages: ["English", "Māori"],
    telephone_code: "+64",
  },
  {
    name: "Palau",
    code: "PW",
    capital: "Ngerulmud",
    population: 18008,
    area: { number: 459, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["English", "Palauan"],
    telephone_code: "+680",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    capital: "Port Moresby",
    population: 8947027,
    area: { number: 462840, measure: "sq km" },
    currency_name: "Papua New Guinean Kina",
    currency_code: "PGK",
    languages: ["English", "Tok Pisin", "Hiri Motu"],
    telephone_code: "+675",
  },
  {
    name: "Samoa",
    code: "WS",
    capital: "Apia",
    population: 198414,
    area: { number: 2831, measure: "sq km" },
    currency_name: "Samoan Tala",
    currency_code: "WST",
    languages: ["Samoan", "English"],
    telephone_code: "+685",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    capital: "Honiara",
    population: 686884,
    area: { number: 28896, measure: "sq km" },
    currency_name: "Solomon Islands Dollar",
    currency_code: "SBD",
    languages: ["English"],
    telephone_code: "+677",
  },
  {
    name: "Tonga",
    code: "TO",
    capital: "Nuku'alofa",
    population: 105695,
    area: { number: 747, measure: "sq km" },
    currency_name: "Tongan Pa'anga",
    currency_code: "TOP",
    languages: ["Tongan", "English"],
    telephone_code: "+676",
  },
  {
    name: "Tuvalu",
    code: "TV",
    capital: "Funafuti",
    population: 11792,
    area: { number: 26, measure: "sq km" },
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    languages: ["Tuvaluan", "English"],
    telephone_code: "+688",
  },
  {
    name: "Vanuatu",
    code: "VU",
    capital: "Port Vila",
    population: 307145,
    area: { number: 12189, measure: "sq km" },
    currency_name: "Vanuatu Vatu",
    currency_code: "VUV",
    languages: ["Bislama", "English", "French"],
    telephone_code: "+678",
  },
];
