export const country = [
  {
    name: "Albania",
    code: "AL",
    capital: "Tirana",
    population: 2877797,
    area: { number: 28748, measure: "sq km" },
    currency_name: "Albanian Lek",
    currency_code: "ALL",
    languages: ["Albanian"],
    telephone_code: "+355",
  },
  {
    name: "Andorra",
    code: "AD",
    capital: "Andorra la Vella",
    population: 77265,
    area: { number: 468, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Catalan"],
    telephone_code: "+376",
  },
  {
    name: "Austria",
    code: "AT",
    capital: "Vienna",
    population: 9006398,
    area: { number: 83879, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["German"],
    telephone_code: "+43",
  },
  {
    name: "Belarus",
    code: "BY",
    capital: "Minsk",
    population: 9449323,
    area: { number: 207600, measure: "sq km" },
    currency_name: "Belarusian Ruble",
    currency_code: "BYN",
    languages: ["Belarusian", "Russian"],
    telephone_code: "+375",
  },
  {
    name: "Belgium",
    code: "BE",
    capital: "Brussels",
    population: 11589623,
    area: { number: 30528, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Dutch", "French", "German"],
    telephone_code: "+32",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    capital: "Sarajevo",
    population: 3280819,
    area: { number: 51209, measure: "sq km" },
    currency_name: "Bosnia and Herzegovina Convertible Mark",
    currency_code: "BAM",
    languages: ["Bosnian", "Croatian", "Serbian"],
    telephone_code: "+387",
  },
  {
    name: "Bulgaria",
    code: "BG",
    capital: "Sofia",
    population: 6948445,
    area: { number: 110879, measure: "sq km" },
    currency_name: "Bulgarian Lev",
    currency_code: "BGN",
    languages: ["Bulgarian"],
    telephone_code: "+359",
  },
  {
    name: "Croatia",
    code: "HR",
    capital: "Zagreb",
    population: 4105267,
    area: { number: 56594, measure: "sq km" },
    currency_name: "Croatian Kuna",
    currency_code: "HRK",
    languages: ["Croatian"],
    telephone_code: "+385",
  },
  {
    name: "Cyprus",
    code: "CY",
    capital: "Nicosia",
    population: 1207359,
    area: { number: 9251, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Greek", "Turkish"],
    telephone_code: "+357",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    capital: "Prague",
    population: 10708981,
    area: { number: 78865, measure: "sq km" },
    currency_name: "Czech Koruna",
    currency_code: "CZK",
    languages: ["Czech"],
    telephone_code: "+420",
  },
  {
    name: "Denmark",
    code: "DK",
    capital: "Copenhagen",
    population: 5792202,
    area: { number: 43094, measure: "sq km" },
    currency_name: "Danish Krone",
    currency_code: "DKK",
    languages: ["Danish"],
    telephone_code: "+45",
  },
  {
    name: "Estonia",
    code: "EE",
    capital: "Tallinn",
    population: 1326535,
    area: { number: 45339, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Estonian"],
    telephone_code: "+372",
  },
  {
    name: "Finland",
    code: "FI",
    capital: "Helsinki",
    population: 5540720,
    area: { number: 338424, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Finnish", "Swedish"],
    telephone_code: "+358",
  },
  {
    name: "France",
    code: "FR",
    capital: "Paris",
    population: 65273511,
    area: { number: 551695, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["French"],
    telephone_code: "+33",
  },
  {
    name: "Germany",
    code: "DE",
    capital: "Berlin",
    population: 83783942,
    area: { number: 357022, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["German"],
    telephone_code: "+49",
  },

  {
    name: "Greece",
    code: "GR",
    capital: "Athens",
    population: 10423054,
    area: { number: 131957, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Greek"],
    telephone_code: "+30",
  },
  {
    name: "Hungary",
    code: "HU",
    capital: "Budapest",
    population: 9660351,
    area: { number: 93028, measure: "sq km" },
    currency_name: "Hungarian Forint",
    currency_code: "HUF",
    languages: ["Hungarian"],
    telephone_code: "+36",
  },
  {
    name: "Iceland",
    code: "IS",
    capital: "Reykjavik",
    population: 341243,
    area: { number: 103000, measure: "sq km" },
    currency_name: "Icelandic Króna",
    currency_code: "ISK",
    languages: ["Icelandic"],
    telephone_code: "+354",
  },
  {
    name: "Ireland",
    code: "IE",
    capital: "Dublin",
    population: 4937786,
    area: { number: 70273, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Irish", "English"],
    telephone_code: "+353",
  },
  {
    name: "Italy",
    code: "IT",
    capital: "Rome",
    population: 60461826,
    area: { number: 301340, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Italian"],
    telephone_code: "+39",
  },
  {
    name: "Kosovo",
    code: "XK",
    capital: "Pristina",
    population: 1810366,
    area: { number: 10908, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Albanian", "Serbian"],
    telephone_code: "+383",
  },
  {
    name: "Latvia",
    code: "LV",
    capital: "Riga",
    population: 1886198,
    area: { number: 64559, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Latvian"],
    telephone_code: "+371",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    capital: "Vaduz",
    population: 38128,
    area: { number: 160, measure: "sq km" },
    currency_name: "Swiss Franc",
    currency_code: "CHF",
    languages: ["German"],
    telephone_code: "+423",
  },
  {
    name: "Lithuania",
    code: "LT",
    capital: "Vilnius",
    population: 2722289,
    area: { number: 65300, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Lithuanian"],
    telephone_code: "+370",
  },
  {
    name: "Luxembourg",
    code: "LU",
    capital: "Luxembourg City",
    population: 625978,
    area: { number: 2586, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Luxembourgish", "French", "German"],
    telephone_code: "+352",
  },

  {
    name: "Malta",
    code: "MT",
    capital: "Valletta",
    population: 441543,
    area: { number: 316, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Maltese", "English"],
    telephone_code: "+356",
  },
  {
    name: "Moldova",
    code: "MD",
    capital: "Chisinau",
    population: 4033963,
    area: { number: 33846, measure: "sq km" },
    currency_name: "Moldovan Leu",
    currency_code: "MDL",
    languages: ["Romanian"],
    telephone_code: "+373",
  },
  {
    name: "Monaco",
    code: "MC",
    capital: "Monaco",
    population: 39242,
    area: { number: 2, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["French"],
    telephone_code: "+377",
  },
  {
    name: "Montenegro",
    code: "ME",
    capital: "Podgorica",
    population: 628066,
    area: { number: 13812, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Montenegrin"],
    telephone_code: "+382",
  },
  {
    name: "Netherlands",
    code: "NL",
    capital: "Amsterdam",
    population: 17134872,
    area: { number: 41543, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Dutch"],
    telephone_code: "+31",
  },
  {
    name: "North Macedonia",
    code: "MK",
    capital: "Skopje",
    population: 2083374,
    area: { number: 25713, measure: "sq km" },
    currency_name: "Macedonian Denar",
    currency_code: "MKD",
    languages: ["Macedonian"],
    telephone_code: "+389",
  },
  {
    name: "Norway",
    code: "NO",
    capital: "Oslo",
    population: 5421241,
    area: { number: 323802, measure: "sq km" },
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
    languages: ["Norwegian"],
    telephone_code: "+47",
  },
  {
    name: "Poland",
    code: "PL",
    capital: "Warsaw",
    population: 37887768,
    area: { number: 312696, measure: "sq km" },
    currency_name: "Polish Złoty",
    currency_code: "PLN",
    languages: ["Polish"],
    telephone_code: "+48",
  },
  {
    name: "Portugal",
    code: "PT",
    capital: "Lisbon",
    population: 10196709,
    area: { number: 92090, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Portuguese"],
    telephone_code: "+351",
  },
  {
    name: "Romania",
    code: "RO",
    capital: "Bucharest",
    population: 19237691,
    area: { number: 238397, measure: "sq km" },
    currency_name: "Romanian Leu",
    currency_code: "RON",
    languages: ["Romanian"],
    telephone_code: "+40",
  },
  {
    name: "Vatican City",
    code: "VA",
    capital: "Vatican City",
    population: 801,
    area: { number: 0.44, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Italian", "Latin"],
    telephone_code: "+379",
  },
  {
    name: "Macedonia",
    code: "MK",
    capital: "Skopje",
    population: 2083374,
    area: { number: 25713, measure: "sq km" },
    currency_name: "Macedonian Denar",
    currency_code: "MKD",
    languages: ["Macedonian"],
    telephone_code: "+389",
  },
  {
    name: "Montenegro",
    code: "ME",
    capital: "Podgorica",
    population: 628066,
    area: { number: 13812, measure: "sq km" },
    currency_name: "Euro",
    currency_code: "EUR",
    languages: ["Montenegrin"],
    telephone_code: "+382",
  },
  {
    name: "Serbia",
    code: "RS",
    capital: "Belgrade",
    population: 8737371,
    area: { number: 77474, measure: "sq km" },
    currency_name: "Serbian Dinar",
    currency_code: "RSD",
    languages: ["Serbian"],
    telephone_code: "+381",
  },
];
