export const country = [
  {
    name: "Antigua and Barbuda",
    code: "AG",
    capital: "St. John's",
    population: 97928,
    area: { number: 442, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-268",
  },
  {
    name: "Bahamas",
    code: "BS",
    capital: "Nassau",
    population: 393244,
    area: { number: 13943, measure: "sq km" },
    currency_name: "Bahamian Dollar",
    currency_code: "BSD",
    languages: ["English"],
    telephone_code: "+1-242",
  },
  {
    name: "Barbados",
    code: "BB",
    capital: "Bridgetown",
    population: 287375,
    area: { number: 430, measure: "sq km" },
    currency_name: "Barbadian Dollar",
    currency_code: "BBD",
    languages: ["English"],
    telephone_code: "+1-246",
  },
  {
    name: "Belize",
    code: "BZ",
    capital: "Belmopan",
    population: 397621,
    area: { number: 22966, measure: "sq km" },
    currency_name: "Belize Dollar",
    currency_code: "BZD",
    languages: ["English"],
    telephone_code: "+501",
  },
  {
    name: "Canada",
    code: "CA",
    capital: "Ottawa",
    population: 38005238,
    area: { number: 9984670, measure: "sq km" },
    currency_name: "Canadian Dollar",
    currency_code: "CAD",
    languages: ["English", "French"],
    telephone_code: "+1",
  },
  {
    name: "Costa Rica",
    code: "CR",
    capital: "San José",
    population: 5047561,
    area: { number: 51100, measure: "sq km" },
    currency_name: "Costa Rican Colón",
    currency_code: "CRC",
    languages: ["Spanish"],
    telephone_code: "+506",
  },
  {
    name: "Cuba",
    code: "CU",
    capital: "Havana",
    population: 11326616,
    area: { number: 110860, measure: "sq km" },
    currency_name: "Cuban Peso",
    currency_code: "CUP",
    languages: ["Spanish"],
    telephone_code: "+53",
  },
  {
    name: "Dominica",
    code: "DM",
    capital: "Roseau",
    population: 71991,
    area: { number: 751, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-767",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    capital: "Santo Domingo",
    population: 10996774,
    area: { number: 48671, measure: "sq km" },
    currency_name: "Dominican Peso",
    currency_code: "DOP",
    languages: ["Spanish"],
    telephone_code: "+1-809, +1-829, +1-849",
  },
  {
    name: "El Salvador",
    code: "SV",
    capital: "San Salvador",
    population: 6486205,
    area: { number: 21041, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["Spanish"],
    telephone_code: "+503",
  },

  {
    name: "Grenada",
    code: "GD",
    capital: "St. George's",
    population: 112003,
    area: { number: 344, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-473",
  },
  {
    name: "Guatemala",
    code: "GT",
    capital: "Guatemala City",
    population: 17915568,
    area: { number: 108889, measure: "sq km" },
    currency_name: "Guatemalan Quetzal",
    currency_code: "GTQ",
    languages: ["Spanish"],
    telephone_code: "+502",
  },
  {
    name: "Haiti",
    code: "HT",
    capital: "Port-au-Prince",
    population: 11577779,
    area: { number: 27750, measure: "sq km" },
    currency_name: "Haitian Gourde",
    currency_code: "HTG",
    languages: ["French", "Haitian Creole"],
    telephone_code: "+509",
  },
  {
    name: "Honduras",
    code: "HN",
    capital: "Tegucigalpa",
    population: 10004529,
    area: { number: 112492, measure: "sq km" },
    currency_name: "Honduran Lempira",
    currency_code: "HNL",
    languages: ["Spanish"],
    telephone_code: "+504",
  },
  {
    name: "Jamaica",
    code: "JM",
    capital: "Kingston",
    population: 2961161,
    area: { number: 10991, measure: "sq km" },
    currency_name: "Jamaican Dollar",
    currency_code: "JMD",
    languages: ["English"],
    telephone_code: "+1-876",
  },
  {
    name: "Mexico",
    code: "MX",
    capital: "Mexico City",
    population: 128932753,
    area: { number: 1964375, measure: "sq km" },
    currency_name: "Mexican Peso",
    currency_code: "MXN",
    languages: ["Spanish"],
    telephone_code: "+52",
  },
  {
    name: "Nicaragua",
    code: "NI",
    capital: "Managua",
    population: 6624554,
    area: { number: 130373, measure: "sq km" },
    currency_name: "Nicaraguan Córdoba",
    currency_code: "NIO",
    languages: ["Spanish"],
    telephone_code: "+505",
  },
  {
    name: "Panama",
    code: "PA",
    capital: "Panama City",
    population: 4314767,
    area: { number: 75420, measure: "sq km" },
    currency_name: "Panamanian Balboa, United States Dollar",
    currency_code: "PAB, USD",
    languages: ["Spanish"],
    telephone_code: "+507",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    capital: "Basseterre",
    population: 53199,
    area: { number: 261, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-869",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    capital: "Castries",
    population: 183627,
    area: { number: 616, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-758",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    capital: "Kingstown",
    population: 110210,
    area: { number: 389, measure: "sq km" },
    currency_name: "Eastern Caribbean Dollar",
    currency_code: "XCD",
    languages: ["English"],
    telephone_code: "+1-784",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    capital: "Port of Spain",
    population: 1399488,
    area: { number: 5130, measure: "sq km" },
    currency_name: "Trinidad and Tobago Dollar",
    currency_code: "TTD",
    languages: ["English"],
    telephone_code: "+1-868",
  },
  {
    name: "United States",
    code: "US",
    capital: "Washington, D.C.",
    population: 331002651,
    area: { number: 9372610, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["English"],
    telephone_code: "+1",
  },
];
