export const country = [
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    population: 45195774,
    area: { number: 2780400, measure: "sq km" },
    currency_name: "Argentine Peso",
    currency_code: "ARS",
    languages: ["Spanish"],
    telephone_code: "+54",
  },
  {
    name: "Bolivia",
    code: "BO",
    capital: "Sucre, La Paz",
    population: 11673021,
    area: { number: 1098581, measure: "sq km" },
    currency_name: "Bolivian Boliviano",
    currency_code: "BOB",
    languages: ["Spanish", "Quechua", "Aymara"],
    telephone_code: "+591",
  },
  {
    name: "Brazil",
    code: "BR",
    capital: "Brasília",
    population: 212559417,
    area: { number: 8515767, measure: "sq km" },
    currency_name: "Brazilian Real",
    currency_code: "BRL",
    languages: ["Portuguese"],
    telephone_code: "+55",
  },
  {
    name: "Chile",
    code: "CL",
    capital: "Santiago",
    population: 19116201,
    area: { number: 756102, measure: "sq km" },
    currency_name: "Chilean Peso",
    currency_code: "CLP",
    languages: ["Spanish"],
    telephone_code: "+56",
  },
  {
    name: "Colombia",
    code: "CO",
    capital: "Bogotá",
    population: 50882891,
    area: { number: 1141748, measure: "sq km" },
    currency_name: "Colombian Peso",
    currency_code: "COP",
    languages: ["Spanish"],
    telephone_code: "+57",
  },
  {
    name: "Ecuador",
    code: "EC",
    capital: "Quito",
    population: 17643054,
    area: { number: 276841, measure: "sq km" },
    currency_name: "United States Dollar",
    currency_code: "USD",
    languages: ["Spanish"],
    telephone_code: "+593",
  },
  {
    name: "Guyana",
    code: "GY",
    capital: "Georgetown",
    population: 786552,
    area: { number: 214969, measure: "sq km" },
    currency_name: "Guyanese Dollar",
    currency_code: "GYD",
    languages: ["English"],
    telephone_code: "+592",
  },
  {
    name: "Paraguay",
    code: "PY",
    capital: "Asunción",
    population: 7132530,
    area: { number: 406752, measure: "sq km" },
    currency_name: "Paraguayan Guarani",
    currency_code: "PYG",
    languages: ["Spanish", "Guaraní"],
    telephone_code: "+595",
  },
  {
    name: "Peru",
    code: "PE",
    capital: "Lima",
    population: 32971846,
    area: { number: 1285216, measure: "sq km" },
    currency_name: "Peruvian Sol",
    currency_code: "PEN",
    languages: ["Spanish"],
    telephone_code: "+51",
  },
  {
    name: "Suriname",
    code: "SR",
    capital: "Paramaribo",
    population: 586632,
    area: { number: 163820, measure: "sq km" },
    currency_name: "Surinamese Dollar",
    currency_code: "SRD",
    languages: ["Dutch"],
    telephone_code: "+597",
  },
  {
    name: "Uruguay",
    code: "UY",
    capital: "Montevideo",
    population: 3473727,
    area: { number: 181034, measure: "sq km" },
    currency_name: "Uruguayan Peso",
    currency_code: "UYU",
    languages: ["Spanish"],
    telephone_code: "+598",
  },
  {
    name: "Venezuela",
    code: "VE",
    capital: "Caracas",
    population: 28435940,
    area: { number: 916445, measure: "sq km" },
    currency_name: "Venezuelan Bolívar",
    currency_code: "VES",
    languages: ["Spanish"],
    telephone_code: "+58",
  },
];
